name: flutter_app
description: "ZAR+ private operational app for gold and currency workflows."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.3
  shamsi_date: 1.1.1
  url_launcher: 6.3.1
  flutter_local_notifications: ^22.3.0
  timezone: ^0.11.1
  shared_preferences: ^2.5.5
  firebase_core: ^4.14.0
  firebase_auth: ^6.6.1
  cloud_firestore: ^6.9.0
  file_selector: ^1.0.4
  share_plus: ^12.0.1
  drift: ^2.34.0
  drift_flutter: ^0.3.1
  file_saver: 0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.10.4
  drift_dev: ^2.34.0

flutter:
  uses-material-design: true
  fonts:
    - family: Vazirmatn
      fonts:
        - asset: assets/fonts/Vazirmatn-Regular.ttf
          weight: 400
        - asset: assets/fonts/Vazirmatn-Medium.ttf
          weight: 500
        - asset: assets/fonts/Vazirmatn-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Vazirmatn-Bold.ttf
          weight: 700
